// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateStudioForAvalonia
{
    internal sealed partial class Vsix
    {
        public const string Id = "TemplateStudioForAvalonia.973b9e25-68ad-44b2-b375-9a775809cb97";
        public const string Name = "Avalonia Template Studio";
        public const string Description = @"Template Studio accelerates the creation of new Avalonia apps using a wizard-based UI.";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Microsoft";
        public const string Tags = "Template Studio, Avalonia, XAML, MVVM, Desktop";
    }
}
